ConfigVersion: 1.0
## If Set To True The Plugin Will Automatically Update The Plugin (And Install On Next Update) When A New Update Is Published On Bukkit
AutoUpdate: true
## If Set To True Any Player With Homespawn.admin Will Receive A Notification If There Is An Update
UpdateNotification: true
## If Set To True The Plugin Will Send Usage Information To mcstats.org, Such As Minecraft Version And Players Online
Metrics: true
## The number of seconds in between save operations will be blocked, so only every x seconds a save will happen
TimeBetweenSaves: 10
## If set to true, inventpory is only saved if it is not empty
SaveOnlyIfNotEmtpy: true
## Also save and restore players spawn location
SaveSpawnLocation: true
